package demo.invoices;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ClientAddress implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Position(value = 0)
   private java.lang.String street;
   @org.kie.api.definition.type.Position(value = 1)
   private java.lang.Integer number;
   @org.kie.api.definition.type.Position(value = 2)
   private java.lang.String cp;
   @org.kie.api.definition.type.Position(value = 3)
   private java.lang.String city;
   @org.kie.api.definition.type.Position(value = 4)
   private java.lang.String country;

   public java.lang.String getStreet()
   {
      return this.street;
   }

   public void setStreet(java.lang.String street)
   {
      this.street = street;
   }

   public java.lang.Integer getNumber()
   {
      return this.number;
   }

   public void setNumber(java.lang.Integer number)
   {
      this.number = number;
   }

   public java.lang.String getCp()
   {
      return this.cp;
   }

   public void setCp(java.lang.String cp)
   {
      this.cp = cp;
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.String getCountry()
   {
      return this.country;
   }

   public void setCountry(java.lang.String country)
   {
      this.country = country;
   }

   public ClientAddress()
   {
   }

   public ClientAddress(java.lang.String street, java.lang.Integer number,
         java.lang.String cp, java.lang.String city, java.lang.String country)
   {
      this.street = street;
      this.number = number;
      this.cp = cp;
      this.city = city;
      this.country = country;
   }

}