package demo.invoices;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Client implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Position(value = 0)
   private java.lang.String name;
   @org.kie.api.definition.type.Position(value = 1)
   private java.lang.String lastName;
   @org.kie.api.definition.type.Position(value = 2)
   private java.util.Date birthday;
   @org.kie.api.definition.type.Position(value = 3)
   private java.lang.String idCard;
   @org.kie.api.definition.type.Position(value = 4)
   private java.lang.String email;
   @org.kie.api.definition.type.Position(value = 5)
   private demo.invoices.ClientAddress address;

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getLastName()
   {
      return this.lastName;
   }

   public void setLastName(java.lang.String lastName)
   {
      this.lastName = lastName;
   }

   public java.util.Date getBirthday()
   {
      return this.birthday;
   }

   public void setBirthday(java.util.Date birthday)
   {
      this.birthday = birthday;
   }

   public java.lang.String getIdCard()
   {
      return this.idCard;
   }

   public void setIdCard(java.lang.String idCard)
   {
      this.idCard = idCard;
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public demo.invoices.ClientAddress getAddress()
   {
      return this.address;
   }

   public void setAddress(demo.invoices.ClientAddress address)
   {
      this.address = address;
   }

   public Client()
   {
   }

   public Client(java.lang.String name, java.lang.String lastName,
         java.util.Date birthday, java.lang.String idCard,
         java.lang.String email, demo.invoices.ClientAddress address)
   {
      this.name = name;
      this.lastName = lastName;
      this.birthday = birthday;
      this.idCard = idCard;
      this.email = email;
      this.address = address;
   }

}