package demo.invoices;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InvoiceLine implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Position(value = 0)
   private java.lang.String product;
   @org.kie.api.definition.type.Position(value = 1)
   private java.lang.Double price;
   @org.kie.api.definition.type.Position(value = 2)
   private java.lang.Double amount;
   @org.kie.api.definition.type.Position(value = 3)
   private java.math.BigDecimal total;

   public java.lang.String getProduct()
   {
      return this.product;
   }

   public void setProduct(java.lang.String product)
   {
      this.product = product;
   }

   public java.lang.Double getPrice()
   {
      return this.price;
   }

   public void setPrice(java.lang.Double price)
   {
      this.price = price;
   }

   public java.lang.Double getAmount()
   {
      return this.amount;
   }

   public void setAmount(java.lang.Double amount)
   {
      this.amount = amount;
   }

   public java.math.BigDecimal getTotal()
   {
      return this.total;
   }

   public void setTotal(java.math.BigDecimal total)
   {
      this.total = total;
   }

   public InvoiceLine()
   {
   }

   public InvoiceLine(java.lang.String product, java.lang.Double price,
         java.lang.Double amount, java.math.BigDecimal total)
   {
      this.product = product;
      this.price = price;
      this.amount = amount;
      this.total = total;
   }

}